%YAML 1.2
---
- name: Install haveged
  yum:
    name: haveged
    state: "{{ haveged_pkg_state }}"

- name: Update init.d
  lineinfile: >
    regexp='(\s*)\$\{HAVEGED_BIN\} -w (\d+)(.*)'
    line="\1${HAVEGED_BIN} -w {{ haveged_low_entropy_watermark }}\3"
    backrefs=yes
    dest="{{ havegad_config_initd_path }}"
    state=present
  notify:
    - restart haveged
...
